apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: wizards-demo
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: wizards-demo
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/sample-accelerators/wizards-demo
      ref:
        branch: main
